<?php
require __DIR__ . '/config.php'; session_name(SESSION_NAME); session_start();
if (isset($_POST['logout'])) { session_destroy(); header('Location: admin.php'); exit; }
if (!($_SESSION['admin'] ?? false)) {
  if ($_SERVER['REQUEST_METHOD']==='POST' && hash_equals(ADMIN_PASSWORD, $_POST['password'] ?? '')) { $_SESSION['admin']=true; header('Location: admin.php'); exit; }
  ?><!doctype html><html lang="ar" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>لوحة المراجعة</title><link rel="stylesheet" href="assets/style.css"></head><body><main class="login"><form method="post"><span class="eyebrow">إدارة الاستبيان</span><h1>لوحة المراجعة</h1><p>أدخل كلمة مرور المشرف.</p><input name="password" type="password" required autofocus placeholder="كلمة المرور"><button class="submit">دخول</button></form></main></body></html><?php exit;
}
$items=load_submissions(); $questions=questions(); $tab=($_GET['tab'] ?? 'reviews') === 'ip' ? 'ip' : 'reviews';
if ($_SERVER['REQUEST_METHOD']==='POST' && isset($_POST['save_review'])) { foreach ($items as &$item) if ($item['id']===$_POST['id']) { $item['decisions']=[]; foreach ($questions as $q) $item['decisions'][$q['id']]=($_POST['decision'][$q['id']] ?? '')==='approved'?'approved':'rejected'; } unset($item); save_submissions($items); header('Location: admin.php?updated=1'); exit; }
if ($_SERVER['REQUEST_METHOD']==='POST' && isset($_POST['withdrawal_id'])) { foreach ($items as &$item) if ($item['id']===$_POST['withdrawal_id']) $item['withdrawal']='paid'; unset($item); save_submissions($items); header('Location: admin.php?paid=1'); exit; }
if ($_SERVER['REQUEST_METHOD']==='POST' && isset($_POST['ip_user_id'])) { $action=$_POST['ip_action'] ?? ''; foreach ($items as &$item) if ($item['id']===$_POST['ip_user_id']) $item['ip_blocked']=$action==='block'; unset($item); save_submissions($items); header('Location: admin.php?tab=ip&ip_updated=1'); exit; }
function balance($item,$questions) { $sum=0; foreach($questions as $q) if (($item['decisions'][$q['id']]??'')==='approved') $sum+=$q['amount']; return $sum; }
?><!doctype html><html lang="ar" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>لوحة المراجعة</title><link rel="stylesheet" href="assets/style.css"></head><body class="admin-body"><main class="admin"><header class="admin-head"><div><span class="eyebrow">إدارة الاستبيان</span><h1>لوحة التحكم</h1></div><form method="post"><button name="logout" class="ghost">تسجيل الخروج</button></form></header>
<nav class="admin-tabs"><a class="<?= $tab==='reviews'?'active':'' ?>" href="admin.php">مراجعة الإجابات</a><a class="<?= $tab==='ip'?'active':'' ?>" href="admin.php?tab=ip">إدارة قيود IP</a></nav>
<?php if(isset($_GET['updated'])):?><p class="flash">تم حفظ قرارات المراجعة وتحديث الرصيد.</p><?php endif; ?><?php if(isset($_GET['ip_updated'])):?><p class="flash">تم تحديث حالة قيد IP للمستخدم.</p><?php endif; ?>
<?php if($tab==='ip'): ?><section class="ip-panel"><h2>إدارة قيود IP</h2><p>المستخدم المحظور لا يستطيع إرسال استبيان آخر من نفس الاتصال. عند الضغط على «السماح بإرسال جديد» يُرفع القيد عنه فقط، وتظل إجابته القديمة محفوظة.</p><?php if(empty($items)): ?><div class="empty">لا توجد مستخدمون حتى الآن.</div><?php endif; ?><?php foreach(array_reverse($items) as $item): $blocked=$item['ip_blocked'] ?? true; ?><article class="ip-user"><div><h3><?= e($item['name']) ?></h3><p><?= e($item['phone']) ?><?= !empty($item['country']) ? ' · '.e($item['country']) : '' ?></p></div><div class="ip-status <?= $blocked?'blocked':'unblocked' ?>"><?= $blocked?'محظور من إرسال جديد':'مسموح بإرسال جديد' ?></div><form method="post"><input type="hidden" name="ip_user_id" value="<?= e($item['id']) ?>"><input type="hidden" name="ip_action" value="<?= $blocked?'unlock':'block' ?>"><button class="<?= $blocked?'unlock-ip':'block-ip' ?>"><?= $blocked?'السماح بإرسال جديد':'إعادة الحظر' ?></button></form></article><?php endforeach; ?></section>
<?php else: ?><?php if(empty($items)): ?><div class="empty">لا توجد إجابات حتى الآن.</div><?php endif; ?><?php foreach(array_reverse($items) as $item): $bal=balance($item,$questions); ?><article class="submission"><div class="submission-top"><div><h2><?= e($item['name']) ?></h2><p><?= e($item['phone']) ?><?= !empty($item['country']) ? ' · '.e($item['country']) : '' ?> · <?= date('Y/m/d H:i',strtotime($item['created_at'])) ?></p></div><div class="balance"><small>الرصيد المعتمد</small><strong><?= $bal ?> جنيه</strong></div></div><form method="post"><input type="hidden" name="id" value="<?= e($item['id']) ?>"><?php foreach($questions as $q): $decision=$item['decisions'][$q['id']]??''; ?><div class="review"><div><span class="review-number"><?= $q['id'] ?></span><h3><?= e($q['text']) ?></h3><p><?= nl2br(e($item['answers'][$q['id']])) ?></p></div><div class="review-actions"><label><input type="radio" name="decision[<?= $q['id'] ?>]" value="approved" <?= $decision==='approved'?'checked':'' ?>> مقبولة +<?= $q['amount'] ?></label><label><input type="radio" name="decision[<?= $q['id'] ?>]" value="rejected" <?= $decision==='rejected'?'checked':'' ?>> مرفوضة</label></div></div><?php endforeach; ?><button class="save" name="save_review">حفظ المراجعة</button></form><?php if($bal>0): ?><div class="withdraw-admin"><span>السحب: <?= $item['withdrawal']==='paid'?'تم التحويل':'بانتظار طلب اللاعب' ?></span><?php if($item['withdrawal']==='requested'): ?><form method="post"><input type="hidden" name="withdrawal_id" value="<?= e($item['id']) ?>"><button class="save">تأكيد التحويل</button></form><?php endif; ?></div><?php endif; ?></article><?php endforeach; ?><?php endif; ?></main></body></html>
